"""Create hotel reservation models

Revision ID: 86dfe1390fc5
Revises: 
Create Date: 2021-10-15 23:34:25.713687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "86dfe1390fc5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hotel",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=250), nullable=True),
        sa.Column("address", sa.String(length=250), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "room",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("number", sa.Integer(), nullable=True),
        sa.Column("hotel_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["hotel_id"],
            ["hotel.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("room")
    op.drop_table("hotel")
    # ### end Alembic commands ###
